name: publish package
permissions:
  contents: read
  pull-requests: write

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libssl-dev
      - uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.9.11"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build package
        run: uv build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b

  release_github:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To create a github release
    steps:
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Create GitHub Release
      id: create_release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: "dist/*"
        generateReleaseNotes: true
